name: Deploy My Fidelity CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run deployment
        env:
          WEB_DEPLOY_METHOD: ${{ secrets.WEB_DEPLOY_METHOD }}
          WEB_DEPLOY_API: ${{ secrets.WEB_DEPLOY_API }}
          WEB_DEPLOY_TOKEN: ${{ secrets.WEB_DEPLOY_TOKEN }}
        run: |
          MAX_RETRIES=3
          MIN_WAIT=60  # Minimum wait in seconds (1 minute)
          MAX_WAIT=180 # Maximum wait in seconds (3 minutes)

          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Deployment attempt $i of $MAX_RETRIES for MyFiCDN..."

            # Run the curl command. If it succeeds, break out of the loop.
            if curl --fail-with-body -X ${WEB_DEPLOY_METHOD} "${WEB_DEPLOY_API}myficdn" -H "Accept: */*" -H "${WEB_DEPLOY_TOKEN}"; then
              echo -e "\nDeployment successful!"
              exit 0
            fi

            # If it fails, check if we have attempts left
            if [ $i -lt $MAX_RETRIES ]; then
              # Calculate random sleep time in seconds
              WAIT_TIME=$((RANDOM % (MAX_WAIT - MIN_WAIT + 1) + MIN_WAIT))
              echo -e "\nDeployment failed. Retrying in $WAIT_TIME seconds..."
              sleep $WAIT_TIME
            else
              echo -e "\nAll $MAX_RETRIES attempts failed."
              exit 1
            fi
          done
