name: Deploy MyFi CDN

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: run deployment
      env:
        WEB_DEPLOY_PREFIX: ${{ secrets.WEB_DEPLOY_PREFIX }}
        WEB_DEPLOY_POSTFIX: ${{ secrets.WEB_DEPLOY_POSTFIX }}
      run: |
        ${env.WEB_DEPLOY_PREFIX}myficdn ${env.WEB_DEPLOY_POSTFIX}
