name: Deploy MyFi CDN

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: run deployment
      env:
        WEB_DEPLOY_METHOD: ${{ secrets.WEB_DEPLOY_METHOD }}
        WEB_DEPLOY_API: ${{ secrets.WEB_DEPLOY_API }}
        WEB_DEPLOY_TOKEN: ${{ secrets.WEB_DEPLOY_TOKEN }}
      run: |
        curl --fail-with-body -X ${WEB_DEPLOY_METHOD} "${WEB_DEPLOY_API}myficdn" -H "Accept: */*" -H "${WEB_DEPLOY_TOKEN}"
